### ISSUE TITLE
Collaborate 🚀 

### ISSUE THREAD

**Issue by stefnotch** [Ephraim-Bryski/seeciv#8]
Welcome! I stumbled upon your site after clicking on the link that you posted over at [sympy](https://github.com/sympy/sympy/discussions/21225#discussioncomment-560319). Then I got around to looking at the GitHub and found your [planning document](https://docs.google.com/document/d/1khY9FJkwpUIDD7Q1wCzWFPmwEtcCwW_puN1Y9zYjKUk/edit)

There, I read the intro and was sold. This sounds amazing, and it sounds a lot like what me and [phcreery](https://github.com/phcreery) are trying to build.
Here is [a little gif](https://imgur.com/gallery/SsAvvZh) of what we already have working.

Some quick notes
> Backend
> - Should all computations be done on the backend (e.g. solving systems of equations)?

As a web developer, I can confirm that one does not need a backend for that. Sympy with Pyodide works really well. [Xcas](https://www-fourier.ujf-grenoble.fr/~parisse/giac.html) is supposedly an excellent option as well. 

> Layout
> - Should React be used?

By all means, do use a framework for something as complex as that. We have opted to use Vue.js.

> User Interface
> ...

That is a very nice and simple user interface. We've opted for something slightly fancier, but the core ideas are the same. 

If you happen to have Discord, I'd love to chat a bit. Either add me `stefnotch#3837` or check out the tiny [QuantumSheet Discord server](https://discord.gg/xatHjgW). If that's not your thing, I'm totally open to anything else, ranging from old fashioned email to video calls through Zoom.

**Comment by Ephraim-Bryski** [comment]
Hi Stefnotch,

It's great to hear that you're interested, and I would love to collaborate
with you. I'm a bit backlogged with work at the moment since the semester
just started, but I will look into QuantumSheet and I'll reach out to you
on Discord (I should be free on the weekend).

-Ephraim
